### ISSUE TITLE
Feature Request - Adding a parameter to only instantiate the encoder

### ISSUE THREAD

**Issue by cyrilzakka** [PPPrior/u2net#1]
Is there an easy way to add a parameter to only instantiate the encoder part of the UNet?

**Comment by PPPrior** [comment]
> Is there an easy way to add a parameter to only instantiate the encoder part of the UNet?

I implement U-Net like encoder-decoder structure by recursion, so it‘s hard to separate encoder.
It may be easier to modify on official code.

**Comment by cyrilzakka** [comment]
I realized after a day of messing with your code and too many 'if' conditions. Thank you anyway and great implementation!
